- content/controls.md
Documentation for origo-map/origo#90
> Add info about measure control

- content/layers.md
- content/settings.md
Short description about subgroups added to groups documentation.
> Added documentation on subgroups

- content/layers.md
> resolution to scale

- content/settings.md
> Rewrote info on proj4Defs

- content/layers.md
> Enhances syntax in examples

- content/layers.md
> Adds id property to WFS layer description

- content/styles.md
> Added alternative WMS style docs

- content/styles.md
> Adds extended legend docs

- content/controls.md
Adds some documentation about progressbar.
> adds progressbar fixes #34

- content/controls.md
> Removed offline control from documentation

- content/controls.md
- content/introduction.md
> Options example

- content/controls.md
> Adds externalUrl docs

- content/layers.md
Fixes #44.
This is what I know about "type": "GROUP". If anything is wrong or missing, please feel free to add it.
> Adds GROUP layers docs

- content/controls.md
- content/layers.md
> Adds editor attribute types

- content/controls.md
> Adds the turnOffLayersControl option to the legend control documentation

- content/settings.md
> Adds the constrainResolution option to the settings documentation

- content/controls.md
> Added info about controls order

- content/layers.md
> Documentation for opacity slider

- content/controls.md
> Added scalepicker documentation

- content/controls.md
> Added elevation data tool docs

- content/layers.md
> Added doc for suffix for layers

- content/layers.md
> Added wmtsStyle parameter docs

- content/controls.md
> Added autoHide docs

- content/styles.md
> Added icon rotation docs

- content/controls.md
> Fix missing comma.

- content/controls.md
> Documentation of print control with config for custom logo.

- content/settings.md
> Adds code example for groups

- content/layers.md
> Adds required to editor attributes

- content/controls.md
> More config options on Print control.

- content/settings.md
Fixes issue #96 .
This pr is depended on pr [#942](https://github.com/origo-map/origo/pull/942) in origo-map being merged.
> Docs for infowindow

- content/settings.md
> Added OL map/view settings docs

- content/controls.md
Config options for north arrow control
> Added more config options on print control

- content/controls.md
> Updated measure control docs

- content/controls.md
> Documenting new options in print control

- content/layers.md
> adds searchlist to attributes list fixes issue 109

- content/layers.md
Adds attribute options targetTitle with description.
> Adds attribute options targetTitle with description.

- content/controls.md
> Documentation of useHectare option in measure control

- content/controls.md
> Added geoposition tracking mode docs

- content/controls.md
> Fullscreen docs

- content/controls.md
> Added Bookmarks control docs

- content/layers.md
> Added layer CSS settings

- content/controls.md
Added documentation and example for copyTool. Also added more documentation for drawTools.
Documentation for origo-map/origo#1223
> Added copy tool

- content/styles.md
> filter, minScale and maxScale

- content/layers.md
> Changes date-time to datetime

- content/controls.md
Documentation for origo-map/origo#1227, option for editor to validate geometries when darwing.
> Added validateOnDraw option.

- content/layers.md
> Documenting new option in editor for multiple constraints value

- content/settings.md
> Embedded map interaction

- content/layers.md
Documentation for origo-map/origo#1281, allowEditOperations.
> Allowed edit operations

- content/controls.md
> Fixes bookmarks' options placement

- content/settings.md
Documentation for origo-map/origo#1292
> Documentation for changePointerOnHover 

- content/layers.md
> Source options wmts

- content/settings.md
> Subgroup toggle all

- content/controls.md
> Documenting showSegmentLabelButtonActive

- content/controls.md
> fix: add new print control option to documentation

- content/introduction.md
Documentation for PR origo-map/origo#1383 
Added mention and example of comments in json.
> Comments in configuration.

- content/layers.md
Documentation for attachments implemented in origo-map/origo#1314.
> Documentation for attachments

- content/controls.md
> Documenting search options

- content/layers.md
> Documenting new options prefix/suffix

- content/controls.md
> Documenting buffer tool in measure control

- content/styles.md
> More documentation

- content/settings.md
Documentation for origo-map/origo#1455
> Documentation for clientExport

- content/layers.md
Documentation for PR origo-map/origo#1398
> Documentation for related layers.

- content/layers.md
- content/settings.md
> Layout fix

- content/layers.md
> Doc infoFormat option

- content/layers.md
> Added zoomToExtent docs

- content/layers.md
Documentation for origo-map/origo#1509
Bonus: documentation for attribute type `hidden`
> Documentation for default values

- content/layers.md
Documentation for origo-map/origo#1515
> Search list documentation

- content/layers.md
> Changed text for "removable"

- content/controls.md
> Adds visibleLayersControl

- content/layers.md
Documentation for origo-map/origo#1533
Also closes #206.
> Checkbox values

- content/layers.md
I've only tested the stylePicker with geojson and wfs, so I will add stylePicker text to those formats. Let me know if I should add text to more formats.
Fixes #219.
> Adds stylePicker to geojson and wfs

- content/styles.md
> Adds header and hidden to styles

- content/settings.md
> Adds round export button and changes simpleExport

- content/layers.md
> feat: add info on WMS auto legend style property

- content/controls.md
> fix: added the control name in the description

- content/layers.md
> fix: changed text for abstract

- content/controls.md
> fix: missing option documentation for sharemap

- content/layers.md
- content/settings.md
> feat: add imagefeatureinfomode

- content/controls.md
> fix: domentation turnOnLayersControl option in legend control

- content/controls.md
> Fix: Print placement

- content/controls.md
Change in documentation as pointed out in origo-map/origo#1709
> fix: changed documentation to reality for editor default state

- content/layers.md
- content/settings.md
Documentation for origo-map/origo#1708
> Documented aggregations

- content/layers.md
> doc: sourceParams option for WMS layers

- content/api.md
- custom/content.js
> New section with Origo API examples

- content/layers.md
- content/settings.md
> doc: carousel option

- content/controls.md
> zoomToExtent for draw control

- content/introduction.md
> doc: clarification on initiating Origo

- content/settings.md
> doc: new multiSelectionStyles

- content/api.md
Added a example of code for API section.
```
// Refresh temperature data every 10 minutes
setInterval(() => {
if (origo.api().getLayer('temperature').getVisible()) {
origo.api().getLayer('temperature').getSource().refresh();
}
}, 600000);
```
> doc: example of refreshing data for layer

- content/controls.md
Documentation for origo-map/origo#1883
> drawTools multigeometries

- content/settings.md
> New group options

- content/layers.md
> fix: more information to attribution

- content/controls.md
- content/settings.md
> Added palette setting

- content/controls.md
> Added docs about search-searchlist

- content/controls.md
> feature: add highlightcolor prop for measure

- content/layers.md
Added a new property "isTrue" with a checkbox type to the layers.md file. This property includes configuration for checked and unchecked values. Also, fixed the missing newline at the end of the file.
> Add isTrue checkbox property to layers.md

- content/layers.md
Fixes #312  in addition to original PR #311
> Fixed syntax and indentation in example

- content/controls.md
Added queryType as search option
> Added queryType

- content/layers.md
Closes #297 
Visual Studio Code did a lot of formatting on the file automatically on save which looks nice in the IDE. If it isn't wanted I could try sending a PR without all the formatting.
> doc: thematicStyling option

- content/styles.md
> More information about how to use style filters.

- content/controls.md
Documentation for origo-map/origo#2084
Adds documentation for search control suppressDialog option.
> Documented search suppressDialog

- content/controls.md
Documentation for origo-map/origo#2124
> Split line

- content/controls.md
> doc: Queryable option for measure control

- content/settings.md
> doc: Adds removable option for groups

- content/settings.md
Documentation for origo-map/origo#2053.
Also, fixes #348.
> Docs and examples of extended layerSpecificExport
